# Generated by Django 4.0.6 on 2022-08-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('OV', 'Organization Validation'), ('DV', 'Domain Validation'), ('Personal', 'Personal')], default='Personal', max_length=255, verbose_name='Тип сертификата'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='short_description',
            field=models.TextField(blank=True, max_length=45, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
