# Generated by Django 4.0.6 on 2022-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_type_alter_stock_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('ov', 'Organization Validation'), ('dv', 'Domain Validation'), ('personal', 'Personal')], default='personal', max_length=255, verbose_name='Тип сертификата'),
        ),
    ]
