# Generated by Django 4.0.6 on 2022-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('Organization Validation', 'Organization Validation'), ('Domain Validation', 'Domain Validation'), ('Personal', 'Personal')], default='Personal', max_length=255, verbose_name='Тип сертификата'),
        ),
    ]
