# Generated by Django 4.0.6 on 2022-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные запроса на сертификат'),
        ),
    ]
